import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { SettingsProvider } from '@/contexts/SettingsContext';
import ErrorBoundary from '@/components/ErrorBoundary';

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <script src="/notification-sound.js" defer />
        <script
          dangerouslySetInnerHTML={{
            __html: `
              // Global error handler to suppress MetaMask extension conflicts
              const originalError = console.error;
              console.error = function(...args) {
                const message = args[0]?.toString() || '';
                if (message.includes('ethereum') || 
                    message.includes('MetaMask') || 
                    message.includes('Cannot set property') ||
                    message.includes('requestProvider') ||
                    message.includes('inpage.js')) {
                  return; // Suppress MetaMask-related errors
                }
                originalError.apply(console, args);
              };
              
              window.addEventListener('error', function(e) {
                if (e.message && (
                  e.message.includes('ethereum') || 
                  e.message.includes('MetaMask') || 
                  e.message.includes('Cannot set property ethereum') ||
                  e.message.includes('requestProvider') ||
                  e.message.includes('inpage.js') ||
                  e.filename?.includes('extension') ||
                  e.filename?.includes('requestProvider') ||
                  e.filename?.includes('inpage')
                )) {
                  e.preventDefault();
                  e.stopPropagation();
                  return false;
                }
              });
              
              window.addEventListener('unhandledrejection', function(e) {
                if (e.reason && e.reason.message && (
                  e.reason.message.includes('ethereum') || 
                  e.reason.message.includes('MetaMask') ||
                  e.reason.message.includes('Cannot set property')
                )) {
                  e.preventDefault();
                  return false;
                }
              });
            `
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ErrorBoundary>
          <SettingsProvider>
            {children}
          </SettingsProvider>
        </ErrorBoundary>
      </body>
    </html>
  );
}
